// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbaudplbdainhftacixn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYXVkcGxiZGFpbmhmdGFjaXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjY0OTMsImV4cCI6MjA1OTEwMjQ5M30.8Rcx0yTcue2FKs722--gc8t37L0LbmOvGxM1abPGkfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);